version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "8197:8197"
  backend:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./packages/api/db.sqlite:/usr/src/app/packages/api/db.sqlite
      - ./packages/api/uploads:/usr/src/app/packages/api/uploads
    ports:
      - "8825:8825"
